### ISSUE TITLE
Resolve imports in test with webpack?

### ISSUE THREAD

**Issue by stephan-v** [spatie/skeleton-vue#3]
First of all thank you for being pioneers in this area since there is scary little amount on unit testing Javascript and Vue in particular.

I have been struggling with settings this up and also run in problems where I got a message from Jest that I was using a runtime-only build from Vue.

This line helped me figure out why:

`import Vue from 'vue/dist/vue.js';`

I simply imported Vue like so:

`import Vue from 'vue';`

I have gotten so accustomed to having Webpack resolve my alias that this is where I fucked up. Is there any way for Jest to become aware of the Webpack file and automatically resolve things like this?

Of course this in itself is a small fix, but it would be handy to have.

**Comment by sebastiandedeyne** [comment]
Jest doesn't have any knowledge about webpack because the code doesn't need to be bundled. The source code does go through babel though. Haven't tried it myself, but there's a babel loader that reads out your webpack config and applies it to your code, maybe give that a shot?

https://www.npmjs.com/package/babel-plugin-webpack-alias
